services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-database-network

  ms-payments:
    container_name: ms-payments
    image: samuelastech/ms-payments
    platform: linux/amd64
    depends_on:
      - database
      - discovery
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - .:/app
      - /app/.m2
    command: ./mvnw spring-boot:run
    environment:
      server.port: 8080
      spring.datasource.url: jdbc:mysql://database:3306/payments?createDatabaseIfNotExist=true
      eureka.client.serviceUrl.defaultZone: http://discovery:8081/eureka/
      eureka.instance.preferIpAddress: 'true'
      eureka.client.registerWithEureka: 'true'
      eureka.client.fetchRegistry: 'true'
    networks:
      - app-database-network
      - microservices-network

volumes:
  mysql-data:
networks:
  app-database-network:
    name: app-database-network
  microservices-network:
    external: true