spring:
  application:
    name: payments
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    username: root
    password: 4149
  jpa:
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 0

resilience4j:
  circuitbreaker:
    instances:
      updateOrder:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s